---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: nginx
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: nginx-port
  selector:
    run: nginx
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: hnandiwada/nginx
    name: nginx
    ports:
    - containerPort: 8080
      name: nginx-port
    resources: {}
    env:
    - name: PORT
      value: "8080"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
